FROM 198245574422.dkr.ecr.us-west-2.amazonaws.com/orbit-dev-env-jupyter-user
#FROM ${jupyter_user_base}

ENV MY_CUSTOM_ENV_VAR COOL

ARG LOCAL_ARG=$SAMPLE_ARG

ADD my-custom-file.txt /home/jovyan/my-custom-file.txt
