-   PluginId: code_commit
    Module: code_commit
-   PluginId: hello_world
    Module: hello_world
    Parameters:
        foo: boo
        xoo: 1234
-   PluginId: team_script_launcher
    Module: team_script_launcher
    Parameters:
        script: |
            i=0
            while [ $i -lt 1 ];
            do
              find /efs/shared/regression -mtime +5 -exec rm {} \;
              sleep 60
            done
            echo "DONE LOOP"
        restartPolicy: Never
-   PluginId: redshift
    Module: redshift
    Parameters:
        enable_user_activity_logging: "true"
        require_ssl: "true"
        use_fips_ssl: "true"
        node_type: "DC2.large"
        number_of_nodes: "2"
-   PluginId: custom_cfn
    Module: custom_cfn
    Parameters:
        CfnTemplatePath: "./bundle/plugins/demo-lake-creator-cfn-template.yaml"
-   PluginId: fast_fs_lustre
    Module: lustre
-   PluginId: overprovisioning1
    Module: overprovisioning
    Parameters:
        replicas: 3
        cpu: 2
        memory: 4G