Name: !ENV ${ORBIT_ENV_NAME::demo-env}
EksSystemMastersRoles:
- !ENV ${ORBIT_ADMIN_ROLE::Admin}
- !ENV ${ORBIT_ADMIN_DEMO_ROLE::Admin}
ScratchBucketArn: !SSM ${/orbit-f/demo-fndn/resources::ScratchBucketArn}
UserPoolId: !SSM ${/orbit-f/demo-fndn/resources::UserPoolId}
SharedEfsFsId: !SSM ${/orbit-f/demo-fndn/resources::SharedEfsFsId}
SharedEfsSgId: !SSM ${/orbit-f/demo-fndn/resources::SharedEfsSgId}
InstallSsmAgent: true
Networking:
    VpcId: !SSM ${/orbit-f/demo-fndn/resources::VpcId}
    PublicSubnets: !SSM ${/orbit-f/demo-fndn/resources::PublicSubnets}
    PrivateSubnets: !SSM ${/orbit-f/demo-fndn/resources::PrivateSubnets}
    IsolatedSubnets: !SSM ${/orbit-f/demo-fndn/resources::IsolatedSubnets}
    Data:
        InternetAccessible: true
        NodesSubnets: !SSM ${/orbit-f/demo-fndn/resources::NodesSubnets}
    Frontend:
        LoadBalancersSubnets: !SSM ${/orbit-f/demo-fndn/resources::LoadBalancersSubnets}
        SslCertArn: arn:aws:acm:us-west-2:885315059846:certificate/a10e0e40-ef5c-44fc-8dd8-b5fd9fc8a333
        CustomDomainName: demo.orbit.oss.aws.dev
ManagedNodegroups:
-   Name: primary-compute
    InstanceType: m5.2xlarge
    LocalStorageSize: 128
    NodesNumDesired: 6
    NodesNumMax: 8
    NodesNumMin: 4
    Labels:
        instance-type: m5.2xlarge
-   Name: primary-gpu
    InstanceType: g4dn.xlarge
    LocalStorageSize: 128
    NodesNumDesired: 1
    NodesNumMax: 4
    NodesNumMin: 0
Teams:
-   Name: lake-admin
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::demo-env}-${AWS_DEFAULT_REGION::us-west-2}-demo-lake-admin-add-policy
    GrantSudo: true
    Fargate: false
    K8Admin: true
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    Plugins: !include lake-admin-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-admin
-   Name: lake-creator
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::demo-env}-${AWS_DEFAULT_REGION::us-west-2}-demo-lake-creator-add-policy
    GrantSudo: true
    Fargate: false
    K8Admin: false
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    Plugins: !include lake-creator-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-creator
-   Name: lake-user
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::demo-env}-${AWS_DEFAULT_REGION::us-west-2}-demo-lake-user-add-policy
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    GrantSudo: true
    Fargate: false
    K8Admin: false
    Plugins: !include lake-user-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-user
