Name: !ENV ${ORBIT_ENV_NAME::dev-env}
CodeartifactDomain: !ENV ${CODEARTIFACT_DOMAIN::}
CodeartifactRepository: !ENV ${CODEARTIFACT_REPOSITORY::}
EksSystemMastersRoles:
- !ENV ${ORBIT_ADMIN_ROLE::Admin}
- !ENV ${ORBIT_ADMIN_DEMO_ROLE::Admin}
ScratchBucketArn: !SSM ${/orbit-foundation/demo-fndn/resources::ScratchBucketArn}
UserPoolId: !SSM ${/orbit-foundation/demo-fndn/resources::UserPoolId}
SharedEfsFsId: !SSM ${/orbit-foundation/demo-fndn/resources::SharedEfsFsId}
SharedEfsSgId: !SSM ${/orbit-foundation/demo-fndn/resources::SharedEfsSgId}
Networking:
    VpcId: !SSM ${/orbit-foundation/demo-fndn/resources::VpcId}
    PublicSubnets: !SSM ${/orbit-foundation/demo-fndn/resources::PublicSubnets}
    PrivateSubnets: !SSM ${/orbit-foundation/demo-fndn/resources::PrivateSubnets}
    IsolatedSubnets: !SSM ${/orbit-foundation/demo-fndn/resources::IsolatedSubnets}
    Data:
        InternetAccessible: true
        NodesSubnets: !SSM ${/orbit-foundation/demo-fndn/resources::NodesSubnets}
    Frontend:
        LoadBalancersSubnets: !SSM ${/orbit-foundation/demo-fndn/resources::LoadBalancersSubnets}
        SslCertArn: !SSM ${/orbit-foundation/demo-fndn/resources::SslCertArn}
ManagedNodegroups:
-   Name: primary-compute
    InstanceType: m5.2xlarge
    LocalStorageSize: 128
    NodesNumDesired: 3
    NodesNumMax: 4
    NodesNumMin: 1
    Labels:
        instance-type: m5.2xlarge
Teams:
-   Name: lake-creator
    Policies:
    - orbit-dev-env-demo-lake-creator-add-policy
    GrantSudo: true
    Fargate: false
    K8Admin: true
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    Plugins: !include lake-creator-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
-   Name: lake-user
    Policies:
    - orbit-dev-env-demo-lake-user-add-policy
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    GrantSudo: true
    Profiles: !include lake-user-profiles.json
    Plugins: !include lake-user-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
