Name: dev-env
CodeartifactDomain: aws-orbit
CodeartifactRepository: python-Repository
Images:
    CodeBuildImage:
        Repository: aws-orbit-code-build-base
        Source: code
        Path: ../Images/CodeBuildImage
        Version: latest
Networking:
    Data:
        InternetAccessible: false
        NodesSubnets: []
    FrontEnd:
        LoadBalancersSubnets: []
