Name: !ENV ${ORBIT_ENV_NAME::nightly-iso}
CodeartifactDomain: !ENV ${CODEARTIFACT_DOMAIN::}
CodeartifactRepository: !ENV ${CODEARTIFACT_REPOSITORY::}
EksSystemMastersRoles:
-   !ENV ${ORBIT_ADMIN_ROLE::Admin}
ScratchBucketArn: !SSM ${/orbit-f/nightly-iso/resources::ScratchBucketArn}
UserPoolId: !SSM ${/orbit-f/nightly-iso/resources::UserPoolId}
SharedEfsFsId: !SSM ${/orbit-f/nightly-iso/resources::SharedEfsFsId}
SharedEfsSgId: !SSM ${/orbit-f/nightly-iso/resources::SharedEfsSgId}
InstallSsmAgent: true
CognitoExternalProvider: !ENV ${COGNITO_EXTERNAL_PROVIDER::}
CognitoExternalProviderLabel: !ENV ${COGNITO_EXTERNAL_PROVIDER_LABEL::}
Networking:
    VpcId: !SSM ${/orbit-f/nightly-iso/resources::VpcId}
    PublicSubnets: !SSM ${/orbit-f/nightly-iso/resources::PublicSubnets}
    PrivateSubnets: !SSM ${/orbit-f/nightly-iso/resources::PrivateSubnets}
    IsolatedSubnets: !SSM ${/orbit-f/nightly-iso/resources::IsolatedSubnets}
    Data:
        InternetAccessible: !ENV ${INTERNET_ACCESSIBLE::false}
        NodesSubnets: !SSM ${/orbit-f/nightly-iso/resources::NodesSubnets}
    Frontend:
        LoadBalancersSubnets: !SSM ${/orbit-f/nightly-iso/resources::LoadBalancersSubnets}
        SslCertArn: !SSM ${/orbit-f/nightly-iso/resources::SslCertArn}
ManagedNodegroups:
-   Name: primary-compute
    InstanceType: m5.2xlarge
    LocalStorageSize: 128
    NodesNumDesired: 4
    NodesNumMax: 8
    NodesNumMin: 1
    Labels:
        instance-type: m5.2xlarge
-   Name: primary-gpu
    InstanceType: g4dn.xlarge
    LocalStorageSize: 128
    NodesNumDesired: 1
    NodesNumMax: 4
    NodesNumMin: 0
Teams:
-   Name: lake-admin
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::nightly-iso}-${AWS_DEFAULT_REGION::}-demo-lake-admin-add-policy
    GrantSudo: true
    Fargate: false
    K8Admin: true
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    Plugins: !include lake-admin-plugins-iso.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-admin
-   Name: lake-creator
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::nightly-iso}-${AWS_DEFAULT_REGION::}-demo-lake-creator-add-policy
    GrantSudo: true
    Fargate: false
    K8Admin: false
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    Plugins: !include lake-creator-plugins-iso.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-creator
-   Name: lake-user
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::nightly-iso}-${AWS_DEFAULT_REGION::}-demo-lake-user-add-policy
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    GrantSudo: true
    Plugins: !include lake-user-plugins-iso.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-user