Name: !ENV ${ORBIT_ENV_NAME::public2}
EksSystemMastersRoles:
-   !ENV ${ORBIT_ADMIN_ROLE::Admin}
ScratchBucketArn: !SSM ${/orbit-f/public2/resources::ScratchBucketArn}
UserPoolId: !SSM ${/orbit-f/public2/resources::UserPoolId}
SharedEfsFsId: !SSM ${/orbit-f/public2/resources::SharedEfsFsId}
SharedEfsSgId: !SSM ${/orbit-f/public2/resources::SharedEfsSgId}
InstallSsmAgent: true
Networking:
    VpcId: !SSM ${/orbit-f/public2/resources::VpcId}
    PublicSubnets: !SSM ${/orbit-f/public2/resources::PublicSubnets}
    PrivateSubnets: !SSM ${/orbit-f/public2/resources::PrivateSubnets}
    IsolatedSubnets: !SSM ${/orbit-f/public2/resources::IsolatedSubnets}
    Data:
        InternetAccessible: !ENV ${INTERNET_ACCESSIBLE::false}
        NodesSubnets: !SSM ${/orbit-f/public2/resources::NodesSubnets}
    Frontend:
        LoadBalancersSubnets: !SSM ${/orbit-f/public2/resources::LoadBalancersSubnets}
        SslCertArn: !SSM ${/orbit-f/public2/resources::SslCertArn}
ManagedNodegroups:
-   Name: primary-compute
    InstanceType: m5.2xlarge
    LocalStorageSize: 128
    NodesNumDesired: 4
    NodesNumMax: 8
    NodesNumMin: 1
    Labels:
        instance-type: m5.2xlarge
Teams:
-   Name: lake-admin
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::public2}-${AWS_DEFAULT_REGION::}-demo-lake-admin-add-policy
    GrantSudo: true
    Fargate: false
    K8Admin: true
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    Plugins: !include lake-admin-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-admin
-   Name: lake-creator
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::public2}-${AWS_DEFAULT_REGION::}-demo-lake-creator-add-policy
    GrantSudo: true
    Fargate: false
    K8Admin: true
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    Plugins: !include lake-creator-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-creator
-   Name: lake-user
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::public2}-${AWS_DEFAULT_REGION::}-demo-lake-user-add-policy
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    GrantSudo: true
    Plugins: !include lake-user-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-user
