apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- ../../../../aws/aws-istio-authz-adaptor/base_v3
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: authzadaptor
  spec:
    template:
      metadata:
        labels:
          orbit/node-type: fargate
