Name: !ENV ${ORBIT_ENV_NAME::trial}
EksSystemMastersRoles:
- !ENV ${ORBIT_ADMIN_ROLE::Admin}
- !ENV ${ORBIT_ADMIN_DEMO_ROLE::Admin}
ScratchBucketArn: !SSM ${/orbit-f/fdn/resources::ScratchBucketArn}
UserPoolId: !SSM ${/orbit-f/fdn/resources::UserPoolId}
SharedEfsFsId: !SSM ${/orbit-f/fdn/resources::SharedEfsFsId}
SharedEfsSgId: !SSM ${/orbit-f/fdn/resources::SharedEfsSgId}
Networking:
    VpcId: !SSM ${/orbit-f/fdn/resources::VpcId}
    PublicSubnets: !SSM ${/orbit-f/fdn/resources::PublicSubnets}
    PrivateSubnets: !SSM ${/orbit-f/fdn/resources::PrivateSubnets}
    IsolatedSubnets: !SSM ${/orbit-f/fdn/resources::IsolatedSubnets}
    Data:
        InternetAccessible: !ENV ${INTERNET_ACCESSIBLE::true}
        NodesSubnets: !SSM ${/orbit-f/fdn/resources::NodesSubnets}
    Frontend:
        LoadBalancersSubnets: !SSM ${/orbit-f/fdn/resources::LoadBalancersSubnets}
        SslCertArn: !SSM ${/orbit-f/fdn/resources::SslCertArn}
ManagedNodegroups:
-   Name: primary-compute
    InstanceType: m5.2xlarge
    LocalStorageSize: 128
    NodesNumDesired: 4
    NodesNumMax: 10
    NodesNumMin: 2
    Labels:
        instance-type: m5.2xlarge
#-   Name: primary-gpu
#    InstanceType: g4dn.xlarge
#    LocalStorageSize: 128
#    NodesNumDesired: 1
#    NodesNumMax: 4
 #   NodesNumMin: 0
Teams:
-   Name: lake-admin
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::trial}-${AWS_DEFAULT_REGION::us-west-2}-demo-lake-admin-add-policy
    GrantSudo: true
    Fargate: false
    K8Admin: true
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    Plugins: !include lake-admin-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-admin
-   Name: lake-creator
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::trial}-${AWS_DEFAULT_REGION::us-west-2}-demo-lake-creator-add-policy
    GrantSudo: true
    Fargate: false
    K8Admin: false
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    Plugins: !include lake-creator-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-creator
-   Name: lake-user
    Policies:
    - !ENV orbit-${ORBIT_ENV_NAME::trial}-${AWS_DEFAULT_REGION::us-west-2}-demo-lake-user-add-policy
    JupyterhubInboundRanges:
    - 0.0.0.0/0
    GrantSudo: true
    Plugins: !include lake-user-plugins.yaml
    EfsLifeCycle: AFTER_7_DAYS
    AuthenticationGroups:
    - lake-user
