apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../../../aws/aws-alb-ingress-controller/overlays/application
patchesStrategicMerge:
# - delete-deployment.yaml
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: alb-ingress-controller
    annotations:
      orbit/annotation: chauncy
