apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../../../aws/aws-alb-ingress-controller/base_v3
patchesStrategicMerge:
# - delete-deployment.yaml
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: alb-ingress-controller
  spec:
    template:
      metadata:
        labels:
          orbit/node-type: fargate
