Name: !ENV ${ORBIT_ENV_NAME::dev-env}
CodeartifactDomain: !ENV ${CODEARTIFACT_DOMAIN::}
CodeartifactRepository: !ENV ${CODEARTIFACT_REPOSITORY::}
EksSystemMastersRoles:
-   !ENV ${ORBIT_ADMIN_ROLE::Admin}
ScratchBucketArn: !SSM ${/orbit-f/dev-env/resources::ScratchBucketArn}
UserPoolId: !SSM ${/orbit-f/dev-env/resources::UserPoolId}
SharedEfsFsId: !SSM ${/orbit-f/dev-env/resources::SharedEfsFsId}
SharedEfsSgId: !SSM ${/orbit-f/dev-env/resources::SharedEfsSgId}
InstallSsmAgent: true
CognitoExternalProvider: !ENV ${COGNITO_EXTERNAL_PROVIDER::}
CognitoExternalProviderLabel: !ENV ${COGNITO_EXTERNAL_PROVIDER_LABEL::}
Networking:
    VpcId: !SSM ${/orbit-f/dev-env/resources::VpcId}
    PublicSubnets: !SSM ${/orbit-f/dev-env/resources::PublicSubnets}
    PrivateSubnets: !SSM ${/orbit-f/dev-env/resources::PrivateSubnets}
    IsolatedSubnets: !SSM ${/orbit-f/dev-env/resources::IsolatedSubnets}
    Data:
        InternetAccessible: !ENV ${INTERNET_ACCESSIBLE::false}
        NodesSubnets: !SSM ${/orbit-f/dev-env/resources::NodesSubnets}
    Frontend:
        LoadBalancersSubnets: !SSM ${/orbit-f/dev-env/resources::LoadBalancersSubnets}
        SslCertArn: !SSM ${/orbit-f/dev-env/resources::SslCertArn}
ManagedNodegroups:
-   Name: primary-compute
    InstanceType: m5.2xlarge
    LocalStorageSize: 128
    NodesNumDesired: 4
    NodesNumMax: 8
    NodesNumMin: 1
    Labels:
        instance-type: m5.2xlarge
-   Name: primary-gpu
    InstanceType: g4dn.xlarge
    LocalStorageSize: 128
    NodesNumDesired: 1
    NodesNumMax: 4
    NodesNumMin: 0
Teams:
-   Name: lake-admin
    GrantSudo: true
    Fargate: false
    K8Admin: true
    JupyterhubInboundRanges:
    - 0.0.0.0/0
-   Name: lake-creator
    GrantSudo: true
    Fargate: false
    K8Admin: false
    JupyterhubInboundRanges:
    - 0.0.0.0/0
-   Name: lake-user
    GrantSudo: false
    JupyterhubInboundRanges: []
